# roles/rhbase/tasks/users.yml
#
# Create groups and users on the system
---
- name: Users | Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ rhbase_user_groups }}"
  tags:
    - rhbase
    - users

- name: Users | Add users
  user:
    name: "{{ item.name }}"
    state: present
    comment: "{{ item.comment }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    createhome: yes
    groups: "{{ ','.join(item.groups) }}"
    password: "{{ item.password }}"
  with_items: "{{ rhbase_users }}"
  tags:
    - rhbase
    - users

- name: "Users | Set up SSH key for user {{ rhbase_ssh_user|default('(not specified)') }}"
  authorized_key:
    user: "{{ rhbase_ssh_user }}"
    key: "{{ rhbase_ssh_key }}"
  when: rhbase_ssh_user is defined
  tags:
    - rhbase
    - users
